### ISSUE TITLE
Regression - Images are not optional

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/chartpress#76]
Looks like #3 has popped up again.

We use chartpress to publish the Dask helm chart but not the Dask docker images. Therefore we have no `images` section in our config. This seems to have broken with the latest release.

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/chartpress", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chartpress.py", line 693, in main
    for image_name, image_config in chart['images'].items():
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'images'
```

**Comment by consideRatio** [comment]
Ah thanks for reporting this, should be easy to setup a test for and avoid in the future.

This is my fault =/ Sorry.
